### ISSUE TITLE
Files missing from commit?

### ISSUE THREAD

**Issue by BurtHarris** [TypeForce/tsread#1]
Hello Sam,

I'm interested in what you are trying to accomplish here.   I've taken a look at the repo, and wonder if there may be some source-files you haven't checked in.   

For example, trying to run tests I get the following:

```
C:\code\tsread>npm test

> tsread@1.0.0 test C:\code\tsread
> tsread src/test.ts

'tsread' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by samvv** [comment]
Hey there,

I think it is because you must `npm link` first; this will put the binary in your `PATH` (not sure on Windows). 

Also make sure you run a `tsc` before testing it. 

And thanks for trying it out; currently I don't know what path I'm going to take with this, as it might be better to embed it into a documentation tool such as `TypeDoc` instead. I need to ponder my head about it for a couple of days.

Regards,
Sam

**Comment by BurtHarris** [comment]
Ah..., I had done 'npm install', didn't think to use `npm link`.   That works better, I'll think about why that is.

I'm primarily working on a typescript port of the [ANTLR 4](http://www.antlr.org/) parser generator, [antlr4ts](https://github.com/tunnelvisionlabs/antlr4ts#readme).   We've ported one of the most of sophisticated parsing software packages to TypeScript, but the document comments are still in Javadoc format.   So far, I've not been very happy with what `TypeDoc` has created from it.

I've considered contributing to the `TypeDoc` project, but I'm afraid it was started with a style too monolithic for my taste.   For  for example it seems to include its own application framework, (perhaps cloned in part from Backbone) and has its own command-line handling, rather than building on other well-documented packages like `yargs`.

**Comment by BurtHarris** [comment]
It looks like you could avoid needing `npm link` by changing the `test` script in **package.json** to read:

```
    "test": "node lib/bin/tsread.js src/test.ts"
```

**Comment by samvv** [comment]
Might be worthwhile for people not wanting to link it. I'll try to fix later this day.

**Comment by samvv** [comment]
And those are _exactly_ my thoughts ... in order to fix that monolithic architecture I'm afraid you need to start from the ground up. That's why it crossed my mind to start a new documentation tool, you will find it [here](https://github.com/TypeForce/tsdoc) if it ever gets off the ground.

**Comment by BurtHarris** [comment]
Yes, perhaps.  I've a few thoughts on the subject, I'll share them on the tsdoc repo.    Closing this issue as it's outlived it's original purpose, but not my interest.
